name = "SimplePIE"
uuid = "035d3dd0-1203-4f60-83b7-4f66b8f1f3f7"
authors = ["Chen Huang"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
